/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bluewhale;

import java.sql.SQLException;
import java.util.Arrays;
import javax.swing.JOptionPane;
import java.util.Calendar;
import com.toedter.calendar.JCalendar;

/**
 *
 * @author Kavindi
 */
public class CheckIn extends javax.swing.JFrame {

    /**
     * Creates new form CheckIn
     */
    //constructor
    public CheckIn() {
        initComponents();
        this.setLocationRelativeTo(null);
        //set cursor to the first text field
        txtName.requestFocus();
        //get the price from the shared class
        double priceK = DataManager.getPriceK();
        //display the price in the price text field
        txtPrice.setText(String.valueOf(priceK));
        //get the array data from the shared class 
        Object[] roomInfo = DataManager.getRoomInfo();
        String roomNo = (String) roomInfo[0];
        txtRNo.setText(roomNo);
        String roomName = (String) roomInfo[1];
        txtRName.setText(roomName);
        String roomType = (String) roomInfo[2];
        txtRType.setText(roomType);
        double roomPrice = Double.parseDouble((String)roomInfo[3]);
        txtPrice.setText(String.valueOf(roomPrice));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        dateOfBirthChooser = new com.toedter.calendar.JDateChooser();
        checkInDateChooser = new com.toedter.calendar.JDateChooser();
        txtName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNationality = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmbGender = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNIC = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtHome = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtPhoneNo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cmbAdults = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        cmbChildren = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtRNo = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtRName = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtRType = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnCheckIn = new javax.swing.JButton();
        chckbxTerms = new java.awt.Checkbox();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Felix Titling", 1, 24)); // NOI18N
        jLabel1.setText("CHECK IN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bluewhale/close.jpg"))); // NOI18N
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, 20, 20));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        dateOfBirthChooser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(dateOfBirthChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 270, 30));

        checkInDateChooser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(checkInDateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 270, 30));

        txtName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 270, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Nationality");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        txtNationality.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtNationality, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 270, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Gender");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        cmbGender.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        getContentPane().add(cmbGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 270, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Date of Birth");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("NIC");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        txtNIC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtNIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 270, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Email Address");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        txtEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 270, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Home Address");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, -1, -1));

        txtHome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 270, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Phone Number");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, -1, -1));

        txtPhoneNo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtPhoneNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneNoActionPerformed(evt);
            }
        });
        getContentPane().add(txtPhoneNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 270, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Adults");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, -1, -1));

        cmbAdults.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmbAdults.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15" }));
        getContentPane().add(cmbAdults, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 270, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Children");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, -1, -1));

        cmbChildren.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmbChildren.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15" }));
        getContentPane().add(cmbChildren, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 270, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Check In Date");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, 99, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Room Number");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 50, 110, -1));

        txtRNo.setEditable(false);
        txtRNo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtRNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 80, 180, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("Room Name");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 120, 100, -1));

        txtRName.setEditable(false);
        txtRName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtRName, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 150, 180, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("Room Type");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 190, 90, -1));

        txtRType.setEditable(false);
        txtRType.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtRType, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 220, 180, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("Price");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 260, 50, -1));

        txtPrice.setEditable(false);
        txtPrice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 290, 180, -1));

        btnBack.setBackground(new java.awt.Color(0, 0, 204));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 440, -1, -1));

        btnCheckIn.setBackground(new java.awt.Color(0, 0, 204));
        btnCheckIn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCheckIn.setForeground(new java.awt.Color(255, 255, 255));
        btnCheckIn.setText("Check In");
        btnCheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckInActionPerformed(evt);
            }
        });
        getContentPane().add(btnCheckIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 440, -1, -1));

        chckbxTerms.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        chckbxTerms.setLabel("I agree to the terms and conditions.");
        getContentPane().add(chckbxTerms, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, -1, -1));
        chckbxTerms.getAccessibleContext().setAccessibleName("I agree the terms and conditions.");
        chckbxTerms.getAccessibleContext().setAccessibleDescription("I agree the terms and conditions.");
        chckbxTerms.getAccessibleContext().setAccessibleParent(btnCheckIn);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bluewhale/bghotel.jpg"))); // NOI18N
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(-370, -200, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
       System.exit(0);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        String SQL = "UPDATE Room SET  availability = '" + "Available"  + "' WHERE roomNo = '" + txtRNo.getText() + "'";
            
        // Execute the query
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            java.sql.Connection connection = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/HotelManagementSystem", "root", "1234");
            java.sql.Statement stm = connection.createStatement();
            
            int rowsUpdated = stm.executeUpdate(SQL);
            
            if (rowsUpdated > 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Table updated successfully!");
                setVisible(false);
                new signIn().setVisible(true);
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Unsuccessfully...Room Not Found!","Error",JOptionPane.ERROR_MESSAGE);
            }
        //exception handling   
        } catch (ClassNotFoundException ex) {
            System.out.println("Driver Not Found");
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
        setVisible(false);
        ManageRoom manage = new ManageRoom();
        manage.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckInActionPerformed
        //implement the calender for date of birth and check in date
        Calendar selectedCheckInDate = checkInDateChooser.getCalendar();
        Calendar selectedDateOfBirth = checkInDateChooser.getCalendar();
        int checkInDay = selectedCheckInDate.get(Calendar.DAY_OF_MONTH) +1;
        int checkInMonth = selectedCheckInDate.get(Calendar.MONTH)+1;
        int checkInYear = selectedCheckInDate.get(Calendar.YEAR);
        int dateOfBirthDay = selectedDateOfBirth.get(Calendar.DAY_OF_MONTH) +1; // Months are 0-based
        int dateOfBirthMonth = selectedDateOfBirth.get(Calendar.MONTH);
        int dateOfBirthYear = selectedDateOfBirth.get(Calendar.YEAR);
        
        String checkInDateForDB = String.format("%02d/%02d/%d", checkInDay, checkInMonth, checkInYear);
        String dateOfBirthForDB = String.format("%02d/%02d/%d", dateOfBirthDay, dateOfBirthMonth, dateOfBirthYear);
        DataManager.setCheckInDateData(checkInDay);
        //for testing
        System.out.println(checkInDateForDB);

String id = txtNIC.getText();
String name = txtName.getText();
String address = txtHome.getText();
String email = txtEmail.getText();
String nationality = txtNationality.getText();
String phoneNo = txtPhoneNo.getText();
String dob = dateOfBirthForDB;
String checkIn = checkInDateForDB;
int adults = Integer.parseInt(cmbAdults.getSelectedItem().toString());
int children = Integer.parseInt(cmbChildren.getSelectedItem().toString());
String gender = (String) cmbGender.getSelectedItem();
String roomNo = txtRNo.getText();
String roomName = txtRName.getText();
String roomType = txtRType.getText();

//set variable for the checkbox
boolean termsFlag = chckbxTerms.getState();

//check the checkbox is checked or not
if (termsFlag == false) {
    JOptionPane.showMessageDialog(this, "Agree to the terms and conditions!", "ERROR", JOptionPane.ERROR_MESSAGE);
} else {
//check the all fields are filled    
if (!id.isEmpty() && !name.isEmpty() && !address.isEmpty() && !email.isEmpty() && !nationality.isEmpty() && !dob.isEmpty() && !checkIn.isEmpty() && !phoneNo.isEmpty() && !gender.isEmpty() && !roomNo.isEmpty() && !roomName.isEmpty() && !roomType.isEmpty()) {
    
    String SQL = "INSERT INTO checkIn (id, name, nationality, gender, dob, adults, children, checkInDate, email, address, phoneNo, roomNo) " +
                 "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

    try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        try (java.sql.Connection connection = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/HotelManagementSystem", "root", "1234"); java.sql.PreparedStatement pstmt = connection.prepareStatement(SQL)) {
            pstmt.setString(1, id);
            pstmt.setString(2, name);
            pstmt.setString(3, nationality);
            pstmt.setString(4, gender);
            pstmt.setString(5, dob);
            pstmt.setInt(6, adults);
            pstmt.setInt(7, children);
            pstmt.setString(8, checkIn);
            pstmt.setString(9, email);
            pstmt.setString(10, address);
            pstmt.setString(11, phoneNo);
            pstmt.setString(12, roomNo);
             // Set the price value            
            pstmt.executeUpdate();
            
            javax.swing.JOptionPane.showMessageDialog(this, "You are checked-in successfully!");
            setVisible(false);
            new Menu().setVisible(true);
            
        }
    //exception handling
    } catch (ClassNotFoundException ex) {
        System.out.println("Driver not found");
    } catch (SQLException ex) {
        System.out.println(ex.getMessage());
    }
} else {
    System.out.println("Hello");
    javax.swing.JOptionPane.showMessageDialog(this, "Sorry, you cannot check in until you fill in all required fields!", "Error", JOptionPane.ERROR_MESSAGE);
}
}
        
    }//GEN-LAST:event_btnCheckInActionPerformed

    private void txtPhoneNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneNoActionPerformed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CheckIn().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCheckIn;
    private javax.swing.JButton btnClose;
    private java.awt.Checkbox chckbxTerms;
    private com.toedter.calendar.JDateChooser checkInDateChooser;
    private javax.swing.JComboBox<String> cmbAdults;
    private javax.swing.JComboBox<String> cmbChildren;
    private javax.swing.JComboBox<String> cmbGender;
    private com.toedter.calendar.JDateChooser dateOfBirthChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHome;
    private javax.swing.JTextField txtNIC;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNationality;
    private javax.swing.JTextField txtPhoneNo;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtRName;
    private javax.swing.JTextField txtRNo;
    private javax.swing.JTextField txtRType;
    // End of variables declaration//GEN-END:variables
}
