/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bluewhale;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Kavindi
 */
public class ForgotP extends javax.swing.JFrame {

    /**
     * Creates new form ForgotP
     */
    public ForgotP() {
        initComponents();
        this.setLocationRelativeTo(null);
        txtEmail.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtQuestion = new javax.swing.JTextField();
        txtAnswer = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        btnSearch = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnSignIn = new javax.swing.JButton();
        btnSignUp = new javax.swing.JLabel();
        btnSearchAnswer = new javax.swing.JButton();
        txtTest = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("BLUE WHALE HOTEL");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bluewhale/close.jpg"))); // NOI18N
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(505, 0, 17, 20));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Forgot Password?");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Email Address");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Security Question");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Answer");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("New Password");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        txtEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 249, -1));

        txtQuestion.setEditable(false);
        txtQuestion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 249, -1));

        txtAnswer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtAnswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 249, -1));

        txtPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 249, -1));

        btnSearch.setBackground(new java.awt.Color(0, 0, 204));
        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, -1, -1));

        btnSave.setBackground(new java.awt.Color(0, 0, 204));
        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        btnSignIn.setBackground(new java.awt.Color(0, 0, 204));
        btnSignIn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSignIn.setForeground(new java.awt.Color(255, 255, 255));
        btnSignIn.setText("Sign In");
        btnSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignInActionPerformed(evt);
            }
        });
        getContentPane().add(btnSignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, -1, -1));

        btnSignUp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSignUp.setForeground(new java.awt.Color(0, 51, 255));
        btnSignUp.setText("Do you want to sign up again ?");
        btnSignUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSignUpMouseClicked(evt);
            }
        });
        getContentPane().add(btnSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, -1, -1));

        btnSearchAnswer.setBackground(new java.awt.Color(0, 51, 204));
        btnSearchAnswer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSearchAnswer.setForeground(new java.awt.Color(255, 255, 255));
        btnSearchAnswer.setText("Search");
        btnSearchAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchAnswerActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearchAnswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, -1, -1));

        txtTest.setEditable(false);
        txtTest.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtTest, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 250, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bluewhale/bg45.jpg"))); // NOI18N
        jLabel8.setText("Search");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1400, -940, 1920, 1330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignInActionPerformed
        setVisible(false);
        signIn signIn = new signIn();
        signIn.setVisible(true);
    }//GEN-LAST:event_btnSignInActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        //check email field is empty
        if (txtEmail.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter your email address!", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            //search where the email in the database user table
            String searchEmail = txtEmail.getText();
            String SQL = "SELECT * FROM User WHERE email = '" + searchEmail + "'";
            try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            java.sql.Connection connection = java.sql.DriverManager.getConnection("jdbc:mysql://localhost/HotelManagementSystem", "root", "1234");
            java.sql.Statement stm = connection.createStatement();
                // Execute the query
                try (java.sql.ResultSet rs = stm.executeQuery(SQL)) {
                    if (rs.next()) {
                        System.out.println("Hello!");
                        txtQuestion.setText(rs.getString("question"));
                    } else {
                        JOptionPane.showMessageDialog(this, "Email not found.","ERROR",JOptionPane.ERROR_MESSAGE);
                        txtQuestion.setText("");
                    }
                }
                    //exception handling
                    } catch (ClassNotFoundException ex) {
                        System.out.println("Driver Not Found");
                    } catch (SQLException ex) {
                        System.out.println(ex.getMessage());
                    }
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        //check the fields are empty
        if(!txtEmail.getText().isEmpty() && !txtQuestion.getText().isEmpty() && !txtAnswer.getText().isEmpty() && !txtPassword.getText().isEmpty() && !txtTest.getText().isEmpty()){
        String password = txtPassword.getText();
        if (password.length() >= 8) {
        //update the password in the database user table 
        String SQL = "UPDATE User SET password = '" + password + "' WHERE email = '" + txtEmail.getText() + "'";
        // Execute the query
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            java.sql.Connection connection = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/HotelManagementSystem", "root", "1234");
            java.sql.Statement stm = connection.createStatement();
            
            int rowsUpdated = stm.executeUpdate(SQL);
            
            if (rowsUpdated > 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Password updated successfully!");
                setVisible(false);
                new signIn().setVisible(true);
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Unsuccessfully...Customer Not Found!","Error",JOptionPane.ERROR_MESSAGE);
            }
        //exception handling   
        } catch (ClassNotFoundException ex) {
            System.out.println("Driver Not Found");
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
        
        } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Password must be 8 characters long.", "Error", JOptionPane.ERROR_MESSAGE);
                txtPassword.setText("");
            }
        
        }else{
            javax.swing.JOptionPane.showMessageDialog(this, "Save Failed !\n Please fill in all required fields.", "Error", JOptionPane.ERROR_MESSAGE);
            clearFields();
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnSignUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignUpMouseClicked
        setVisible(false);
        SignUp signUp = new SignUp();
        signUp.setVisible(true);
    }//GEN-LAST:event_btnSignUpMouseClicked

    private void btnSearchAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchAnswerActionPerformed
        //check the answer field is empty
        if (txtAnswer.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter your answer for the required question!", "ERROR", JOptionPane.ERROR_MESSAGE);
            } else {
                //search the answer column related to the user input from database
                String searchAnswer = txtAnswer.getText();
                String SQL1 = "SELECT * FROM User WHERE answer = '" + searchAnswer + "'";
                try {
                    Class.forName("com.mysql.cj.jdbc.Driver");
                    java.sql.Connection connection = java.sql.DriverManager.getConnection("jdbc:mysql://localhost/HotelManagementSystem", "root", "1234");
                    java.sql.Statement stmt = connection.createStatement();
                    try (java.sql.ResultSet rst = stmt.executeQuery(SQL1)) {
                        if (rst.next()) {
                            System.out.println("Correct Answer!");
                            txtTest.setText("Your answer is correct.");
                            } else {
                                javax.swing.JOptionPane.showMessageDialog(this, "Incorrect Answer!\n Please enter the correct answer you entered before.", "ERROR", JOptionPane.ERROR_MESSAGE);
                                txtEmail.setText("");
                                txtQuestion.setText("");
                                txtAnswer.setText("");
                            }
                    //exception handling
                    } catch (SQLException ex) {
                    Logger.getLogger(ForgotP.class.getName()).log(Level.SEVERE, null, ex);
                }
            //exception handling                   
            } catch (ClassNotFoundException ex) { 
                Logger.getLogger(ForgotP.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(ForgotP.class.getName()).log(Level.SEVERE, null, ex);
            } 
        }
    }//GEN-LAST:event_btnSearchAnswerActionPerformed
    //methods to clear fields
    public void clearFields(){
        txtEmail.setText("");
        txtQuestion.setText("");
        txtAnswer.setText("");
        txtTest.setText("");
        txtPassword.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSearchAnswer;
    private javax.swing.JButton btnSignIn;
    private javax.swing.JLabel btnSignUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtAnswer;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtQuestion;
    private javax.swing.JTextField txtTest;
    // End of variables declaration//GEN-END:variables
}
