/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bluewhale;

import java.sql.SQLException;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kavindi
 */
public class ManageRoom extends javax.swing.JFrame {

    /**
     * Creates new form ManageRoom
     */
    public ManageRoom() {
        initComponents();
        this.setLocationRelativeTo(null);
        Object[] pricePerDayData = {42000, 42000, 42000, 42000, 27000, 27000, 27000, 27000, 27000, 35000, 35000, 35000, 48000, 48000, 48000, 48000, 0};
        DataManager.setPricePerDayData(pricePerDayData);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textField2 = new javax.swing.JTextField();
        textField1 = new javax.swing.JTextField();
        cmbRName1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbBreakfast = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        btnAddRoom = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblManageRoom = new javax.swing.JTable();
        btnShow = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textField2.setEditable(false);
        textField2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        textField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField2ActionPerformed(evt);
            }
        });
        getContentPane().add(textField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, 210, 30));

        textField1.setEditable(false);
        textField1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        textField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField1ActionPerformed(evt);
            }
        });
        getContentPane().add(textField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, 210, 30));

        cmbRName1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmbRName1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Your Room Number", "R001", "R002", "R003", "R004", "R005", "R006", "R007", "R008", "R009", "R010", "R011", "R012", "R013", "R014", "R015", "R016" }));
        cmbRName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRName1ActionPerformed(evt);
            }
        });
        getContentPane().add(cmbRName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, 210, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Room Number");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, 100, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Room Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, 90, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Room Type");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, 80, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setText("Breakfast - Rs. 5 000.00");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, 190, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Do you want breakfast?");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 380, 170, 20));

        cmbBreakfast.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmbBreakfast.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "YES", "NO" }));
        cmbBreakfast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBreakfastActionPerformed(evt);
            }
        });
        getContentPane().add(cmbBreakfast, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 410, 210, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Price");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 450, 37, -1));

        txtPrice.setEditable(false);
        txtPrice.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPriceActionPerformed(evt);
            }
        });
        getContentPane().add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 480, 210, -1));

        btnAddRoom.setBackground(new java.awt.Color(0, 0, 204));
        btnAddRoom.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddRoom.setForeground(new java.awt.Color(255, 255, 255));
        btnAddRoom.setText("Add Room");
        btnAddRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddRoomActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 520, -1, -1));

        btnBack.setBackground(new java.awt.Color(0, 0, 204));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 520, -1, -1));

        jLabel1.setFont(new java.awt.Font("Felix Titling", 1, 24)); // NOI18N
        jLabel1.setText("MANAGE ROOM");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bluewhale/close.jpg"))); // NOI18N
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 0, 17, 18));

        tblManageRoom.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Room No", "Room Name", "Room Type", "Capacity", "Price per Day", "Availability"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblManageRoom);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, 410));

        btnShow.setBackground(new java.awt.Color(0, 0, 204));
        btnShow.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnShow.setForeground(new java.awt.Color(255, 255, 255));
        btnShow.setText("Show the Rooms");
        btnShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowActionPerformed(evt);
            }
        });
        getContentPane().add(btnShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 520, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bluewhale/bghotel.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-430, -110, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
       System.exit(0);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        setVisible(false);
        new Menu().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowActionPerformed
        DefaultTableModel model = (DefaultTableModel) tblManageRoom.getModel();
        model.setRowCount(0);
        String SQL = "SELECT * FROM Room";
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            java.sql.Connection connection = java.sql.DriverManager.getConnection("jdbc:mysql://localhost/HotelManagementSystem", "root", "1234");
            java.sql.Statement stm = connection.createStatement();
            java.sql.ResultSet rs = stm.executeQuery(SQL);

            while (rs.next()) {
                String roomNo = rs.getString("roomNo");
                String roomName = rs.getString("roomName");
                String roomType = rs.getString("roomType");
                String capacity = rs.getString("capacity");
                double priceDay = rs.getDouble("priceDay");
                String availability = rs.getString("availability");

                model.addRow(new Object[]{roomNo,roomName, roomType, capacity, priceDay, availability});
            }
        } catch (ClassNotFoundException ex) {
            System.out.println("Driver Not Found");
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        } 
    }//GEN-LAST:event_btnShowActionPerformed

    private void cmbBreakfastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBreakfastActionPerformed
        // TODO add your handling code here:
        int breakfastOption = cmbBreakfast.getSelectedIndex();
        int roomNumberManageRoom = cmbRName1.getSelectedIndex();
        double basePrice = 0.0;
        //Object[] pricePerDay = new;
        
        switch (roomNumberManageRoom) {
            case 1, 2, 3, 4 -> {
                textField1.setText("Premium Suite");
                basePrice = 42000;
                }
            case 5, 6, 7, 8, 9 -> {
                textField1.setText("Premium Single Room");
                basePrice = 27000;
                }
            case 10, 11, 12 -> {
                textField1.setText("Executive Double Room");
                basePrice = 35000;
                }
            case 13, 14, 15, 16 -> {
                textField1.setText("Executive Quad Room");
                basePrice = 48000;
                }
            default -> textField1.setText("Unknown Room Type");
        }
        switch (roomNumberManageRoom) {
            case 1, 2, 3, 4, 8, 9, 10, 11, 12, 13, 14, 15, 16 -> textField2.setText("A/C");
            case 5, 6, 7 -> textField2.setText("Non A/C");
            default -> {
            }
        }
        System.out.println(breakfastOption);
        switch (breakfastOption) {
            case 1 -> basePrice += 5000;
            case 2 -> basePrice += 0;
            default -> System.out.println("No Breakfast option selected.");
        }
        DataManager.setPriceK(basePrice);
        double priceK = DataManager.getPriceK();
        txtPrice.setText(String.valueOf(priceK));
        
    }//GEN-LAST:event_cmbBreakfastActionPerformed

    private void txtPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPriceActionPerformed

    private void btnAddRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRoomActionPerformed
        // TODO add your handling code here:
        /*
        double price = Double.parseDouble(txtPrice.getText());
        DataManager.setPriceK(price);
        */
        if ((cmbBreakfast.getSelectedIndex() == 0) || (cmbRName1.getSelectedIndex() == 0)) {
            JOptionPane.showMessageDialog(this, "Please select the room number and whether you want breakfast", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            Object[] roomInfo = new Object[4];
            roomInfo[0] = cmbRName1.getSelectedItem();
            roomInfo[1] = textField1.getText();
            roomInfo[2] = textField2.getText();
            roomInfo[3] = txtPrice.getText();
            DataManager.setRoomInfo(roomInfo);
            System.out.println(Arrays.toString(roomInfo));
            
            String SQL = "UPDATE Room SET  availability = '" + "Not Available"  + "' WHERE roomNo = '" + cmbRName1.getSelectedItem() + "'";
            
        // Execute the query
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            // Get the database connection
            java.sql.Connection connection = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/HotelManagementSystem", "root", "1234");
            java.sql.Statement stm = connection.createStatement();
            
            int rowsUpdated = stm.executeUpdate(SQL);
            
            if (rowsUpdated > 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Table updated successfully!");
                setVisible(false);
                new signIn().setVisible(true);
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Unsuccessfully...Room Not Found!","Error",JOptionPane.ERROR_MESSAGE);
            }
        //exception handling   
        } catch (ClassNotFoundException ex) {
            System.out.println("Driver Not Found");
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
        
            setVisible(false);
            new CheckIn().setVisible(true);
        }
    }//GEN-LAST:event_btnAddRoomActionPerformed

    private void cmbRName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRName1ActionPerformed
        // TODO add your handling code here:
        int breakfastOption = cmbBreakfast.getSelectedIndex();
        int roomNumberManageRoom = cmbRName1.getSelectedIndex();
        double basePrice = 0.0;
        switch (roomNumberManageRoom) {
            case 1, 2, 3, 4 -> {
                textField1.setText("Premium Suite");
                basePrice = 42000;
                }
            case 5, 6, 7, 8, 9 -> {
                textField1.setText("Premium Single Room");
                basePrice = 27000;
                }
            case 10, 11, 12 -> {
                textField1.setText("Executive Double Room");
                basePrice = 35000;
                }
            case 13, 14, 15, 16 -> {
                textField1.setText("Executive Quad Room");
                basePrice = 48000;
                }
            default -> textField1.setText("Unknown Room Type");
        }
        switch (roomNumberManageRoom) {
            case 1, 2, 3, 4, 8, 9, 10, 11, 12, 13, 14, 15, 16 -> textField2.setText("A/C");
            case 5, 6, 7 -> textField2.setText("Non A/C");
            default -> {
            }
        }
        System.out.println(breakfastOption);
        switch (breakfastOption) {
            case 1 -> basePrice += 5000;
            case 2 -> basePrice += 0;
            default -> System.out.println("No Breakfast option selected.");
        }
        DataManager.setPriceK(basePrice);
        double priceK = DataManager.getPriceK();
        txtPrice.setText(String.valueOf(priceK));
    }//GEN-LAST:event_cmbRName1ActionPerformed

    private void textField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField2ActionPerformed

    private void textField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ManageRoom().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddRoom;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnShow;
    private javax.swing.JComboBox<String> cmbBreakfast;
    private javax.swing.JComboBox<String> cmbRName1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblManageRoom;
    private javax.swing.JTextField textField1;
    private javax.swing.JTextField textField2;
    private javax.swing.JTextField txtPrice;
    // End of variables declaration//GEN-END:variables
}
