/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bluewhale;

import java.sql.SQLException;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author Kavindi
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    //constructor
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
        //populate the array
        Object[] roomInfo = new Object[4];
        roomInfo[0] = "0";
        roomInfo[1] = "0";
        roomInfo[2] = "0";
        roomInfo[3] = "0";
        DataManager.setRoomInfo(roomInfo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        btnRooms = new javax.swing.JButton();
        btnManage = new javax.swing.JButton();
        btnCheckIn = new javax.swing.JButton();
        btnCheckOut = new javax.swing.JButton();
        btnBill = new javax.swing.JButton();
        btnSignOut = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Felix Titling", 1, 24)); // NOI18N
        jLabel1.setText("HOME PAGE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 6, -1, -1));

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bluewhale/close.jpg"))); // NOI18N
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(578, 0, 17, 17));

        btnRooms.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRooms.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bluewhale/manage room.png.jpg"))); // NOI18N
        btnRooms.setText("Rooms");
        btnRooms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRoomsActionPerformed(evt);
            }
        });
        getContentPane().add(btnRooms, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 53, 138, -1));

        btnManage.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnManage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bluewhale/manage room.png.jpg"))); // NOI18N
        btnManage.setText("Manage Room");
        btnManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageActionPerformed(evt);
            }
        });
        getContentPane().add(btnManage, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 53, -1, -1));

        btnCheckIn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCheckIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bluewhale/checkin.jpg"))); // NOI18N
        btnCheckIn.setText("Check In");
        btnCheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckInActionPerformed(evt);
            }
        });
        getContentPane().add(btnCheckIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 145, -1, -1));

        btnCheckOut.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCheckOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bluewhale/checkout.jpg"))); // NOI18N
        btnCheckOut.setText("Check Out");
        btnCheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckOutActionPerformed(evt);
            }
        });
        getContentPane().add(btnCheckOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 145, 183, -1));

        btnBill.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bluewhale/bill.jpg"))); // NOI18N
        btnBill.setText("Bill");
        btnBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBillActionPerformed(evt);
            }
        });
        getContentPane().add(btnBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 145, 140, -1));

        btnSignOut.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSignOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bluewhale/logout.png.jpg"))); // NOI18N
        btnSignOut.setText("Sign Out");
        btnSignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignOutActionPerformed(evt);
            }
        });
        getContentPane().add(btnSignOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 53, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bluewhale/hotellogo.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bluewhale/bghotel.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-600, -90, 1200, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnRoomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRoomsActionPerformed
        setVisible(false);
        RoomsHotel rooms = new RoomsHotel();
        rooms.setVisible(true);
    }//GEN-LAST:event_btnRoomsActionPerformed

    private void btnManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageActionPerformed
        setVisible(false);
        ManageRoom manage = new ManageRoom();
        manage.setVisible(true);
    }//GEN-LAST:event_btnManageActionPerformed

    private void btnCheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckInActionPerformed
        Object[] roomInfo = new Object[4];
        roomInfo[0] = "0";
        roomInfo[1] = "0";
        roomInfo[2] = "0";
        roomInfo[3] = "0";
        DataManager.setRoomInfo(roomInfo);
        //warn the user that a room has not been reserved
        if (roomInfo[0] == "0" || roomInfo[1] == "0" || roomInfo[2] == "0" || roomInfo[3] == "0") {
            JOptionPane.showMessageDialog(this, "You have not reserved any rooms.", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            setVisible(false);
            CheckIn checkin = new CheckIn();
            checkin.setVisible(true);
            System.out.println(Arrays.toString(DataManager.getRoomInfo()));
        }

    }//GEN-LAST:event_btnCheckInActionPerformed

    private void btnCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckOutActionPerformed
        setVisible(false);
        CheckOut checkout = new CheckOut();
        checkout.setVisible(true);
    }//GEN-LAST:event_btnCheckOutActionPerformed

    private void btnBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBillActionPerformed
        String value = JOptionPane.showInputDialog(this, "Input your NIC");
        if (value == null || value.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter your NIC", "ERROR", JOptionPane.QUESTION_MESSAGE);
            setVisible(true);
        } else {
            //int Ok = JOptionPane.OK_OPTION;

            setVisible(false);
            Bill bill = new Bill();
            bill.setVisible(true);
        }

    }//GEN-LAST:event_btnBillActionPerformed

    private void btnSignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignOutActionPerformed
        int value = JOptionPane.showConfirmDialog(this, "Do you want to Sign Out ?");
        if (value == JOptionPane.YES_OPTION) {
            setVisible(false);
            signIn signIn = new signIn();
            signIn.setVisible(true);
        } else {
            setVisible(true);
        }
    }//GEN-LAST:event_btnSignOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Menu().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBill;
    private javax.swing.JButton btnCheckIn;
    private javax.swing.JButton btnCheckOut;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnManage;
    private javax.swing.JButton btnRooms;
    private javax.swing.JButton btnSignOut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
