/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bluewhale;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;



/**
 *
 * @author Kavindi
 */
public class signIn extends javax.swing.JFrame {

    /**
     * Creates new form signIn
     */
    public signIn() {
        initComponents();
        this.setLocationRelativeTo(null);
        txtEmail.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        btnSignIn = new javax.swing.JButton();
        btnSignIUp = new javax.swing.JLabel();
        btnForgot = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("BLUE WHALE HOTEL");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 6, -1, -1));

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bluewhale/close.jpg"))); // NOI18N
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(507, 0, 20, 20));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Sign In");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 72, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Email Address");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 144, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Password");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        txtEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 141, 265, -1));

        txtPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 265, -1));

        btnSignIn.setBackground(new java.awt.Color(0, 0, 204));
        btnSignIn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSignIn.setForeground(new java.awt.Color(255, 255, 255));
        btnSignIn.setText("Sign In");
        btnSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignInActionPerformed(evt);
            }
        });
        getContentPane().add(btnSignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, -1, -1));

        btnSignIUp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSignIUp.setForeground(new java.awt.Color(0, 102, 255));
        btnSignIUp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSignIUp.setText("Don't you have an account ? SignUp");
        btnSignIUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSignIUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSignIUpMouseClicked(evt);
            }
        });
        getContentPane().add(btnSignIUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 210, -1));

        btnForgot.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnForgot.setForeground(new java.awt.Color(0, 102, 255));
        btnForgot.setText("Forgotten Password ?");
        btnForgot.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnForgot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnForgotMouseClicked(evt);
            }
        });
        getContentPane().add(btnForgot, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 130, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bluewhale/bg45.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1390, -1020, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignInActionPerformed
        String searchEmail = txtEmail.getText();
        String searchPassword = txtPassword.getText();
        //check the all fields are filled by the user.
        if (!searchEmail.isEmpty()&& !searchPassword.isEmpty()) {
            //Give the approval to the admin page
            if ("Admin@gmail.com".equals(searchEmail) && "admin123".equals(searchPassword)) {
                setVisible(false);
                new Admin().setVisible(true);
            } else {
        //Go to the database and check the relevant id and password which is entered by the user.        
        String SQL = "SELECT * FROM User WHERE email = '" + searchEmail + "' AND password = '" + searchPassword + "'";
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            java.sql.Connection connection = java.sql.DriverManager.getConnection("jdbc:mysql://localhost/HotelManagementSystem", "root", "1234");
            java.sql.Statement stm = connection.createStatement();
                
                // Execute the query
                try (java.sql.ResultSet rs = stm.executeQuery(SQL)) {
                    if (rs.next()) {
                        // User found
                        System.out.println("Email : "+rs.getString("email"));
                        System.out.println("Password : "+rs.getString("password"));
                        System.out.println("Name : "+rs.getString("name"));
                        javax.swing.JOptionPane.showMessageDialog(this, "Login successful!", "Success", ICONIFIED);
                        // Redirect to next screen or functionality
                        setVisible(false);
                        new Menu().setVisible(true);
                        
                    } else {
                        // User not found
                        javax.swing.JOptionPane.showMessageDialog(this, "Incorrect email or password. Please try again.","ERROR",JOptionPane.ERROR_MESSAGE);
                        clearFields();
                    }
                }
                    //exception handling
                    } catch (ClassNotFoundException ex) {
                        System.out.println("Driver Not Found");
                    } catch (SQLException ex) {
                        System.out.println(ex.getMessage());
                    }
            }
        } else {
            //user enter the incorrect information
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter your correct Email address and Password!");
            clearFields();
        }
System.out.println("Hello");
        
    }//GEN-LAST:event_btnSignInActionPerformed

    private void btnSignIUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignIUpMouseClicked
        //enter to the sign up page
        setVisible(false);
        SignUp signUp = new SignUp();
        signUp.setVisible(true);
    }//GEN-LAST:event_btnSignIUpMouseClicked

    private void btnForgotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnForgotMouseClicked
        //enter to the fogotten password page
        setVisible(false);
        ForgotP forgot = new ForgotP();
        forgot.setVisible(true);
    }//GEN-LAST:event_btnForgotMouseClicked

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed
    //clear the fields
    public void clearFields(){
    txtEmail.setText(null);
    txtPassword.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JLabel btnForgot;
    private javax.swing.JLabel btnSignIUp;
    private javax.swing.JButton btnSignIn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
